%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/rbirger/Dropbox/Yale/Typhoid Pitzer Lab/AMR/ARVacProject/MatlabCode/MarinaAMRupdates/Tables/FQNcountry.csv
%
% Auto-generated by MATLAB on 04-Mar-2021 20:57:26

%% FQNS Country: Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Country", "ISO3", "Alpha", "Beta"];
opts.SelectedVariableNames = ["Country", "ISO3", "Alpha", "Beta"];
opts.VariableTypes = ["string", "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Country", "ISO3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Country", "ISO3"], "EmptyFieldRule", "auto");

% Import the data
FQNcountry = readtable("DataFiles/FQNcountry.csv", opts);


%% Clear temporary variables
clear opts
%% FQNS Regions: Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Regions", "Alpha", "Beta"];
opts.SelectedVariableNames = ["Regions", "Alpha", "Beta"];
opts.VariableTypes = ["string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Regions"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Regions"], "EmptyFieldRule", "auto");

% Import the data
FQNregion = readtable("DataFiles/FQNregion.csv", opts);


%% Clear temporary variables
clear opts
%% MDR Countries: Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Country", "ISO3", "Alpha", "Beta"];
opts.SelectedVariableNames = ["Country", "ISO3", "Alpha", "Beta"];
opts.VariableTypes = ["string", "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Country", "ISO3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Country", "ISO3"], "EmptyFieldRule", "auto");

% Import the data
MDRcountry = readtable("DataFiles/MDRcountry.csv", opts);


%% Clear temporary variables
clear opts

%% MDR Regions: Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Regions", "Alpha", "Beta"];
opts.SelectedVariableNames = ["Regions", "Alpha", "Beta"];
opts.VariableTypes = ["string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Regions"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Regions"], "EmptyFieldRule", "auto");

% Import the data
MDRregion = readtable("DataFiles/MDRregion.csv", opts);


%% Clear temporary variables
clear opts
%% Country Regions: Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Country", "ISO3", "Region"];
opts.VariableTypes = ["string", "string", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Country", "ISO3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Country", "ISO3", "Region"], "EmptyFieldRule", "auto");

% Import the data
CountryRegion = readtable("DataFiles/ResData73_BetaDist.csv", opts);


%% Clear temporary variables
clear opts
