%% Import data from Resistance spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/rbirger/Dropbox/Yale/Typhoid Pitzer Lab/AMR/ARVacProject/MatlabCode/ResData.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 04-Apr-2020 17:37:46

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:B74";

% Specify column names and types
opts.VariableNames = ["Country", "ISO3"];
opts.VariableTypes = ["string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Country", "ISO3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Country", "ISO3"], "EmptyFieldRule", "auto");


% Import the data
tbl = readtable("DataFiles/ResData73.xlsx", opts, "UseExcel", false);

%% Convert to output type
Country = tbl.Country;
ISO3 = tbl.ISO3;
%% Clear temporary variables
clear opts tbl

%% Import sheet with country data
%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "CollectedDRs";
opts.DataRange = "A2:C91";

% Specify column names and types
opts.VariableNames = ["Country", "Fq", "MDR"];
opts.VariableTypes = ["categorical", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Country", "EmptyFieldRule", "auto");

% Import the data
CountryDRData = readtable("DataFiles/ResData73.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Import sheet with country regions
%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Sheet3";
opts.DataRange = "A2:B61";

% Specify column names and types
opts.VariableNames = ["Country", "Region"];
opts.VariableTypes = ["string", "categorical"];

% Specify variable properties
opts = setvaropts(opts, "Country", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Country", "Region"], "EmptyFieldRule", "auto");

% Import the data
CountryRegion = readtable("DataFiles/ResData73.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Import sheet with regional data
%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Sheet4";
opts.DataRange = "A2:G10";

% Specify column names and types
opts.VariableNames = ["Region", "MDRMean", "MDRMin", "MDRMax", "FqMean", "FqMin", "FqMax"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Region", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Region", "EmptyFieldRule", "auto");

% Import the data
RegionDRData = readtable("DataFiles/ResData73.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

